[[redirects]]
  from = "https://www.tycoonhq.com/"
  to = "https://www.notion.so/emailsplease/*"
  status = 200
  force = true
  headers = {X-From = "Netlify"}
[[headers]]
  for = "/*"
  [headers.values]
    Access-Control-Allow-Origin = "*"
